### ISSUE TITLE
Apply Reset CSS for all elements 

### ISSUE THREAD

**Issue by shreejilucifer** [VaibhavKothi/iei#3]
https://github.com/VaibhavKothi/iei/blob/46da48bced868c790807ba5cf65b025e5626d573/CSS/home.css#L2

```css
* { 
margin: 0; 
padding: 0; 
}
```
